
services:
  postgres:
    image: postgres:17
    container_name: task_flow_postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_flow_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: task_flow_api
    restart: always

    ports:
      - "4000:4000"

    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      RUST_LOG: ${RUST_LOG}

    depends_on:
       postgres:
         condition: service_healthy


volumes:
  postgres_data:
